# -*- coding: utf-8 -*-
"""pdf_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_o_eBF4VzGDQ__RAZjKEoig2Otia8aX8
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("data.csv")
df.head()

df.columns

x = df["no2"].dropna()
x = x.values

r = 102303635

a_r = 0.05 * (r % 7)
b_r = 0.3 * (r % 5 + 1)

print(a_r, b_r)

z = x + a_r * np.sin(b_r * x)

mu = np.mean(z)
sigma2 = np.var(z)

lambda_ = 1 / (2 * sigma2)
c = 1 / np.sqrt(2 * np.pi * sigma2)

print("mu =", mu)
print("lambda =", lambda_)
print("c =", c)

plt.hist(z, bins=50, density=True)


z_range = np.linspace(min(z), max(z), 1000)
pdf = c * np.exp(-lambda_ * (z_range - mu)**2)

plt.plot(z_range, pdf)
plt.show()